[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.1"
  NEXT_TELEMETRY_DISABLED = "1"
  # NETLIFY_NEXT_PLUGIN_SKIP = "true" # Usually not recommended, let the plugin run

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js static files
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

# Rewrite for Next.js API routes - make this more specific for the routes that caused errors
[[redirects]]
  from = "/api/projects/*"
  to = "/.netlify/functions/nextjs-server/api/projects/:splat"
  status = 200

[[redirects]]
  from = "/api/blog/*"
  to = "/.netlify/functions/nextjs-server/api/blog/:splat"
  status = 200

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/nextjs-server/api/admin/:splat"
  status = 200

[[redirects]]
  from = "/api/github/*"
  to = "/.netlify/functions/nextjs-server/api/github/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/nextjs-server/admin/:splat"
  status = 200

# Rewrite for other API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server/api/:splat"
  status = 200

# Rewrite for other paths
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server/:splat"
  status = 200
  force = false

# Custom headers to handle caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=60"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800" 