[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.1"
  NEXT_TELEMETRY_DISABLED = "1"
  # Better compatibility with Next.js 14
  NEXT_LOCATION = "/"
  NEXT_USE_NETLIFY_EDGE = "true"
  # Ensure Supabase variables are available during build
  NEXT_PUBLIC_SUPABASE_URL = "${NEXT_PUBLIC_SUPABASE_URL}"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "${NEXT_PUBLIC_SUPABASE_ANON_KEY}"
  SUPABASE_SERVICE_ROLE_KEY = "${SUPABASE_SERVICE_ROLE_KEY}"
  NEXT_PUBLIC_SUPABASE_BUCKET = "profolio-bucket"

# Configure the Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js static and JavaScript chunks
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200
  force = true

# Add these high-priority redirects for page chunks
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200
  force = true

# Explicitly handle the root path
[[redirects]]
  from = "/"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true

# Dynamic content pages (with higher priority)
[[redirects]]
  from = "/projects/*"
  to = "/.netlify/functions/nextjs-server/projects/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/blog/*"
  to = "/.netlify/functions/nextjs-server/blog/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/research/*"
  to = "/.netlify/functions/nextjs-server/research/:splat"
  status = 200
  force = true

# Dynamic API routes
[[redirects]]
  from = "/api/projects/*"
  to = "/.netlify/functions/nextjs-server/api/projects/:splat"
  status = 200

[[redirects]]
  from = "/api/research-projects/*"
  to = "/.netlify/functions/nextjs-server/api/research-projects/:splat"
  status = 200

[[redirects]]
  from = "/api/blog/*"
  to = "/.netlify/functions/nextjs-server/api/blog/:splat"
  status = 200

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/nextjs-server/api/admin/:splat"
  status = 200

[[redirects]]
  from = "/api/github/*"
  to = "/.netlify/functions/nextjs-server/api/github/:splat"
  status = 200

# Admin routes
[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/nextjs-server/admin/:splat"
  status = 200

# Timeline route specifically
[[redirects]]
  from = "/timeline"
  to = "/.netlify/functions/nextjs-server/timeline"
  status = 200
  force = true

# Rewrite for other API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server/api/:splat"
  status = 200

# Rewrite for other paths
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server/:splat"
  status = 200
  force = false

# Custom headers to handle caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=60"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800" 